/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compress(input: Buffer | Uint8Array): Buffer | Uint8Array

export declare function uncompress(
  input: Buffer | Uint8Array,
  maxLength?: number | undefined | null,
): Buffer | Uint8Array
